C++ Reflection Generator: generator Namespace Reference
generator Namespace Reference
Functions
std::string generate_enum_reflection (const data::enum_model &mymodel)
std::string generate_enum_reflection (const std::vector< data::enum_model > &myenums, const data::file_model &myfile)
std::string generate_struct_reflection (const data::struct_model &mymodel)
std::string generate_struct_reflection (const std::vector< data::struct_model > &mystructs, const data::file_model &myfile)
Function Documentation
std::string generator::generate_enum_reflection (const data::enum_model & mymodel)
generate code. howto: http://stackoverflow.com/questions/476272/how-to-properly-overload-the-operator-for-an-ostream
Parameters
mymodel the enum model element to be generated
Returns
the generated code
generate the code for one single enum.
Parameters
mymodel the enum to be generated.
Definition at line 111 of file enum_codegenerator.cpp.
Referenced by generate_enum_reflection(), and main().
{
     std::stringstream out;
     out << "namespace reflection {" << std::endl;
     out << "  template<>" << std::endl;
     out << "  struct Enum<" << mymodel.fullname << "> {" << std::endl;
     out << "    //using int_type  = " << mymodel.int_type_name << ";" << std::endl;
     out << "    using enum_type = " << mymodel.fullname << ";" << std::endl;
     out << generate_enum_reflection_for_each(mymodel, "    ") << std::endl;
     out << generate_enum_reflection_str_functions(mymodel, "    ") << std::endl;
     out << "  private:" << std::endl;
     out << generate_enum_reflection_private_maps(mymodel, "    ") << std::endl;
     out << "  };" << std::endl;
     out << "}" << std::endl;
     out << generate_enum_reflection_free_stream_functions(mymodel) << std::endl;
     return out.str();
 }
std::string generator::generate_enum_reflection (const std::vector< data::enum_model > & myenums, const data::file_model & myfile)
generate the code for a set of enums.
Parameters
myenums the collection of enums to be generated.
Definition at line 128 of file enum_codegenerator.cpp.
{
     std::stringstream out;
     out << "namespace reflection {" << std::endl;
     out << "  template<class T>" << std::endl;
     out << "  struct Enum {};" << std::endl;
     out << "}" << std::endl;
     for(auto m: myenums) {
         out << std::endl;
         out << "// ---------------------------" << std::endl;
         out << "// " << m.str() << std::endl;
         out << "// ---------------------------" << std::endl;
         out << generate_enum_reflection(m) << std::endl;
     }
     return out.str();
 }
std::string generator::generate_struct_reflection (const data::struct_model & mymodel)
generate code. howto: http://stackoverflow.com/questions/476272/how-to-properly-overload-the-operator-for-an-ostream
Parameters
mymodel the struct model element to be generated
Returns
the generated code
generate the code for one single struct.
Parameters
mymodel the struct to be generated.
Definition at line 67 of file struct_codegenerator.cpp.
Referenced by generate_struct_reflection(), and main().
{
     std::stringstream out;
     out << "namespace reflection {" << std::endl;
     out << generate_struct_reflection_for_each(mymodel, "    ") << std::endl;
     out << "}" << std::endl;
     //out << generate_struct_reflection_free_stream_functions(mymodel) << std::endl;
     return out.str();
 }
std::string generator::generate_struct_reflection (const std::vector< data::struct_model > & mystructs, const data::file_model & myfile)
generate the code for a set of structs.
Parameters
mystructs the collection of structs to be generated.
Definition at line 76 of file struct_codegenerator.cpp.
{
     std::stringstream out;
     //out << "namespace reflection {" << std::endl;
     //out << "  template<class T>" << std::endl;
     //out << "  struct Struct { T data; };" << std::endl;
     //out << "}" << std::endl;
     for(auto m: mystructs) {
         out << std::endl;
         out << "// ---------------------------" << std::endl;
         out << "// " << m.str() << std::endl;
         out << "// ---------------------------" << std::endl;
         out << generate_struct_reflection(m) << std::endl;
     }
     return out.str();
 }