C++ Reflection Generator: anonymous_namespace{enum_codegenerator.cpp} Namespace Reference
anonymous_namespace{enum_codegenerator.cpp} Namespace Reference
Functions
std::string generate_enum_reflection_for_each (const data::enum_model &mymodel, std::string intend="")
std::string generate_enum_reflection_private_maps (const data::enum_model &mymodel, std::string intend="")
std::string generate_enum_reflection_str_functions (const data::enum_model &mymodel, std::string intend="")
std::string generate_enum_reflection_free_stream_functions (const data::enum_model &mymodel, std::string intend="")
Function Documentation
std::string anonymous_namespace{enum_codegenerator.cpp}::generate_enum_reflection_for_each (const data::enum_model & mymodel, std::string intend = "")
internal: generate a "for each possible value"-function.
Parameters
mymodel the enum model element to be generated
intend a string (spaces) to be inserted in front of each line.
Definition at line 19 of file enum_codegenerator.cpp.
Referenced by generator::generate_enum_reflection().
{
     std::stringstream out;
     out << intend << "static void for_each_possible_value(std::function<void("<< mymodel.fullname <<")> f) {" << std::endl;
     for(auto value: mymodel.value_names) {
         out << intend << "  f(" << mymodel.fullname << "::" << value << ");" << std::endl;
     }
     out << intend << "}" << std::endl;
     return out.str();
 }
std::string anonymous_namespace{enum_codegenerator.cpp}::generate_enum_reflection_free_stream_functions (const data::enum_model & mymodel, std::string intend = "")
internal: generate stream operators. howto: http://stackoverflow.com/questions/476272/how-to-properly-overload-the-operator-for-an-ostream
Parameters
mymodel the enum model element to be generated
intend a string (spaces) to be inserted in front of each line.
Definition at line 92 of file enum_codegenerator.cpp.
Referenced by generator::generate_enum_reflection().
{
     std::stringstream out;
     out << intend << "std::ostream& operator<< (std::ostream& mystream, const "<< mymodel.fullname <<"& myvalue) {" << std::endl;
     out << intend << "  mystream << reflection::Enum<"<< mymodel.fullname <<">::str(myvalue);" << std::endl;
     out << intend << "  return mystream;" << std::endl;
     out << intend << "}" << std::endl;
     return out.str();
 }
std::string anonymous_namespace{enum_codegenerator.cpp}::generate_enum_reflection_private_maps (const data::enum_model & mymodel, std::string intend = "")
internal: generate a name-value map and vice versa.
Parameters
mymodel the enum model element to be generated
intend a string (spaces) to be inserted in front of each line.
Definition at line 34 of file enum_codegenerator.cpp.
Referenced by generator::generate_enum_reflection().
{
     std::stringstream out;
     out << intend << "static const std::map<" << mymodel.fullname << ", std::string>& get_value_name_map() {" << std::endl;
     out << intend << "  static std::map<" << mymodel.fullname << ", std::string> m({" << std::endl;
     for(auto value: mymodel.value_names) {
         out << intend << "    {" << mymodel.fullname << "::" << value << ", \"" << value<<"\"}," << std::endl;
     }
     out << intend << "  });" << std::endl;
     out << intend << "  return m;" << std::endl;
     out << intend << "}" << std::endl;
     out << intend << "static const std::map<std::string, " << mymodel.fullname << ">& get_name_value_map() {" << std::endl;
     out << intend << "  static std::map<std::string, " << mymodel.fullname << "> m({" << std::endl;
     for(auto value: mymodel.value_names) {
         out << intend << "    {\"" << value<<"\"," << mymodel.fullname << "::" << value << "}," << std::endl;
     }
     out << intend << "  });" << std::endl;
     out << intend << "  return m;" << std::endl;
     out << intend << "}" << std::endl;
     return out.str();
 }
std::string anonymous_namespace{enum_codegenerator.cpp}::generate_enum_reflection_str_functions (const data::enum_model & mymodel, std::string intend = "")
internal: generate string conversion functions.
Parameters
mymodel the enum model element to be generated
intend a string (spaces) to be inserted in front of each line.
Definition at line 61 of file enum_codegenerator.cpp.
Referenced by generator::generate_enum_reflection().
{
     std::stringstream out;
     out << intend << "static const char* str("<< mymodel.fullname <<" v) {" << std::endl;
     out << intend << "  auto r = get_value_name_map().find(v);" << std::endl;
     out << intend << "  if (r!=get_value_name_map().end()) {" << std::endl;
     out << intend << "    return r->second.c_str();" << std::endl;
     out << intend << "  }" << std::endl;
     out << intend << "  else {" << std::endl;
     out << intend << "    throw std::invalid_argument(\"unexpected enum value\");" << std::endl;
     out << intend << "  }" << std::endl;
     out << intend << "}" << std::endl;
     out << intend << "static "<< mymodel.fullname <<" parse(const char* txt) {" << std::endl;
     out << intend << "  auto r = get_name_value_map().find(txt);" << std::endl;
     out << intend << "  if (r!=get_name_value_map().end()) {" << std::endl;
     out << intend << "    return r->second;" << std::endl;
     out << intend << "  }" << std::endl;
     out << intend << "  else {" << std::endl;
     out << intend << "    throw std::invalid_argument(\"text did not match any enum value representation\");" << std::endl;
     out << intend << "  }" << std::endl;
     out << intend << "}" << std::endl;
     return out.str();
 }