C++ Reflection Generator: parser::clangstuff Namespace Reference
parser::clangstuff Namespace Reference
Functions
llvm::cl::OptionCategory MyToolCategory ("clang_reflection_generator options")
llvm::cl::opt< bool > useDBFiles ("useDBFiles", cl::desc("with this switch all files from the compilation database are processed.\nThe compilation database can be created with cmake using 'set(CMAKE_EXPORT_COMPILE_COMMANDS ON)'"), cl::cat(MyToolCategory))
llvm::cl::opt< std::string > outFilename ("outFilename", cl::desc("specify the output filename"), cl::init("reflection.h"), cl::value_desc("filename"), cl::cat(MyToolCategory))
llvm::cl::opt< std::string > regexpFilter ("regexpFilter", cl::desc("filter enum (type names)"), cl::init(".*"), cl::value_desc("regexp"), cl::cat(MyToolCategory))
llvm::cl::extrahelp CommonHelp (CommonOptionsParser::HelpMessage)
llvm::cl::extrahelp MoreHelp (R"(This tools allows to extract reflection information from a code base and create reflection code for enums.)")
Variables
CommonOptionsParser * OptionsParser
llvm::cl::OptionCategory MyToolCategory
llvm::cl::opt< bool > useDBFiles
llvm::cl::opt< std::string > outFilename
llvm::cl::opt< std::string > regexpFilter
llvm::cl::extrahelp CommonHelp
llvm::cl::extrahelp MoreHelp
Detailed Description
here, we hide some global variabes shared by all parsers. These variables are used to parse and represent the command line options.
Function Documentation
llvm::cl::extrahelp parser::clangstuff::CommonHelp (CommonOptionsParser::HelpMessage)
CommonOptionsParser declares HelpMessage with a description of the common command-line options related to the compilation database and input files. It's nice to have this help message in all tools.
llvm::cl::extrahelp parser::clangstuff::MoreHelp (R"(This tools allows to extract reflection informationfrom a code base and create reflection code for enums.)")
A help message for this specific tool can be added afterwards.
llvm::cl::OptionCategory parser::clangstuff::MyToolCategory ("clang_reflection_generator options")
Apply a custom category to all command-line options so that they are the only ones displayed.
Referenced by parser::common_parser().
llvm::cl::opt<std::string> parser::clangstuff::outFilename ("outFilename" , cl:: desc"specify the output filename", cl:: init"reflection.h", cl:: value_desc"filename", cl:: catMyToolCategory)
command line option
Referenced by parser::common_parser().
llvm::cl::opt<std::string> parser::clangstuff::regexpFilter ("regexpFilter" , cl:: desc"filter enum (type names)", cl:: init".*", cl:: value_desc"regexp", cl:: catMyToolCategory)
command line option
Referenced by parser::common_parser().
llvm::cl::opt<bool> parser::clangstuff::useDBFiles ("useDBFiles" , cl:: desc"with this switch all files from the compilation database are processed.\nThe compilation database can be created with cmake using 'set(CMAKE_EXPORT_COMPILE_COMMANDS ON)'", cl:: catMyToolCategory)
command line option
Variable Documentation
llvm::cl::extrahelp parser::clangstuff::CommonHelp
CommonOptionsParser declares HelpMessage with a description of the common command-line options related to the compilation database and input files. It's nice to have this help message in all tools.
llvm::cl::extrahelp parser::clangstuff::MoreHelp
A help message for this specific tool can be added afterwards.
llvm::cl::OptionCategory parser::clangstuff::MyToolCategory
Apply a custom category to all command-line options so that they are the only ones displayed.
clang::tooling::CommonOptionsParser * parser::clangstuff::OptionsParser
Definition at line 37 of file common_parser.cpp.
Referenced by parser::common_parser(), parser::enum_parser(), and parser::struct_parser().
llvm::cl::opt<std::string> parser::clangstuff::outFilename
command line option
llvm::cl::opt<std::string> parser::clangstuff::regexpFilter
command line option
llvm::cl::opt<bool> parser::clangstuff::useDBFiles
command line option
Referenced by parser::enum_parser(), and parser::struct_parser().