C++ Reflection Generator: parser Namespace Reference
parser Namespace Reference
Namespaces
clangstuff
Functions
int common_parser (int argc, const char **argv, data::file_model &myfile)
int enum_parser (int argc, const char **argv, const data::file_model &myfile, std::vector< data::enum_model > &myenums)
int struct_parser (int argc, const char **argv, const data::file_model &myfile, std::vector< data::struct_model > &mystructs)
Function Documentation
int parser::common_parser (int argc, const char ** argv, data::file_model & myfile)
Main entry point of the enum parser.
Definition at line 43 of file common_parser.cpp.
Referenced by main().
{
     int ret = EXIT_SUCCESS;
     using namespace parser::clangstuff;
     try
     {
         OptionsParser = new CommonOptionsParser(argc, argv, MyToolCategory);
         //std::cout << "outFilename=" << outFilename.getValue() << std::endl;
         //std::cout << "useDBFiles=" << useDBFiles.getValue() << std::endl;
         myfile.outfile_name=outFilename.getValue();
         myfile.regexp_filter=regexpFilter.getValue();
         // compute guard (from filename)
         myfile.guard = myfile.outfile_name;
         std::transform(myfile.guard.begin(), myfile.guard.end(),
             myfile.guard.begin(), [](char c) -> char {
                 if (not ::isalnum(c)) {
                     return '_';
                 }
                 else {
                     return static_cast<char>(::toupper(c));
                 }
             });
         // end compute guard
     }
     catch(std::exception& ex) {
         cerr << ex.what() << endl;
         return EXIT_FAILURE;
     }
     return ret;
 }
int parser::enum_parser (int argc, const char ** argv, const data::file_model & myfile, std::vector< data::enum_model > & myenums)
Parse the input given as command line arguments. store all found enums in "myenums".
Parameters
argc command line arguments
argv command line arguments
myenums result variable
myfile file model
Returns
0 in case of no errors. Else return the clang error code.
Definition at line 178 of file enum_parser.cpp.
Referenced by main().
{
     int ret = EXIT_SUCCESS;
     using namespace parser::clangstuff;
     try
     {
         // make enum model and filter globally availabe in this file
         global_enum_collection = &myenums;
         filter = std::regex(myfile.regexp_filter);
         // determine input files
         std::vector<std::string> files;
         if (useDBFiles.getValue())
         {
             files = OptionsParser->getCompilations().getAllFiles();
         }
         else
         {
             files = OptionsParser->getSourcePathList();
         }
         ClangTool Tool(OptionsParser->getCompilations(),files);
         //ret |= Tool.run(newFrontendActionFactory(&Finder).get());
         ret |= Tool.run(newFrontendActionFactory<EnumAction>().get());
     }
     catch(std::exception& ex) {
         cerr << ex.what() << endl;
         return EXIT_FAILURE;
     }
     global_enum_collection = nullptr;
     return ret;
 }
int parser::struct_parser (int argc, const char ** argv, const data::file_model & myfile, std::vector< data::struct_model > & mystructs)
Parse the input given as command line arguments. store all found enums in "mystructs".
Parameters
argc command line arguments
argv command line arguments
myfile file model (input)
myenums result variable (output)
Returns
0 in case of no errors. Else return the clang error code.
Definition at line 287 of file struct_parser.cpp.
Referenced by main().
{
     int ret = EXIT_SUCCESS;
     using namespace parser::clangstuff;
     global_struct_collection = &mystructs;
     try
     {
         filter = std::regex(myfile.regexp_filter);
         std::vector<std::string> files;
         if (useDBFiles.getValue())
         {
             files = OptionsParser->getCompilations().getAllFiles();
         }
         else
         {
             files = OptionsParser->getSourcePathList();
         }
         ClangTool Tool(OptionsParser->getCompilations(),files);
         //ret |= Tool.run(newFrontendActionFactory(&Finder).get());
         ret |= Tool.run(newFrontendActionFactory<StructAction>().get());
     }
     catch(std::exception& ex) {
         cerr << ex.what() << endl;
         return EXIT_FAILURE;
     }
     global_struct_collection = nullptr;
     return ret;
 }